resercher_name = input("ФИО исследователя: ")
date = input("Дата: ")
experiment = input("Название эксперимента: ")
conclusion = input("Вывод: ")
with open("journal.txt", "w", encoding="utf-8") as file:
    file.write("+" + "-" * 50 + "+\n")
    file.write(f"| {'Электронный лабораторный журнал':<48} |\n")
    file.write("+" + "-" * 50 + "+\n")
    file.write(f"|{'ФИО исследователя  :   '+ resercher_name:<50}|\n")
    file.write(f"|{'Дата  : '+ date:<50}|\n")
    file.write(f"|{'Название эксперимента: '+ experiment:<50}|\n")
    file.write("+" + "-" * 50 + "+\n")
    file.write(f"|{'Вывод : '+ conclusion:<50}|\n")
    file.write("+" + "-" * 50 + "+\n")
print("\nДанные успешно сохранены в файл journal.txt")