f = open("result.txt", "w", encoding="utf-8")
print("Информация обо мне:", file=f)
print("ФИО: Баранова Елизавета Александровна", file=f)
print("Группа: 4731901/50002", file=f)
print("Направление: Биотехнология", file=f)
print("Год обучения: 1", file=f)
print("Университет: СПбПУ", file=f)
print("Хобби: сноубординг, танцы, настольные игры, чтение", file=f)
f.close()